[theme]
primaryColor = "#2E8B57"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1B2230"
textColor = "#FFFFFF"
font = "sans serif"

[client]
showErrorDetails = true

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[server]
headless = true
enableCORS = false
